#!/usr/bin/env python3
"""rewrite.py — 改写闭环（产改写卡 + diff/入库），内核不调 LLM。

时序: pre → 写 → post → [rewrite] → Agent 改写 → [accept]

- run_rewrite: 读原文 + post 产出的去重报告 → generate_tasks → 写「改写卡」md
  + revision_tasks.json。正文改写由 Agent host 执行，本函数不调任何模型。
- run_accept: 原文 vs revised → generate_diff_report → 写 diff/log；当 ingest=True
  且 recommendation 非 REJECTED 时，把 revised 提升为该章 canonical 并入库（追加
  chapter_versions 快照，永不覆盖原稿）。
"""

import difflib
import json
from pathlib import Path

from version import get_version
from src.pipeline._base import (
    App,
    find_chapter_file_with_fallback,
    _strip_selfcheck,
    _resolve_slot_db_path,
    load_config,
    write_json_atomic,
)
from src.pipeline.revision_task_generator import generate_tasks, split_paragraphs
from src.pipeline.revision_diff_report import generate_diff_report
from src.pipeline.ingest import ingest as ingest_chapter
from src.pipeline.semantic_contract import (
    build_preservation_contract,
    lexical_precheck,
    read_verdict,
    evaluate_preservation,
    write_review_request,
)


def _semantic_paths(app, chapter_file, chapter_no):
    """语义保全三件套路径：请求 json / host 卡 md / host 回执 json。"""
    reports_dir = app.exports_root / "reports"
    card_dir = app.outputs_root / "rewrite_cards"
    return (
        reports_dir / f"chapter_{chapter_no:03d}_semantic_review_request.json",
        card_dir / f"chapter_{chapter_no:03d}_semantic_review.md",
        chapter_file.parent / f"chapter_{chapter_no:03d}_semantic_review.json",
    )


def _build_context(novel_slug, novel_title, volume_no, chapters_dir,
                   db_path, project_root, config_path):
    """构建 App，沿用 run_post 的 context-or-build 模式。"""
    cfg = load_config(config_path, project_root=project_root)
    if db_path:
        cfg["db_path"] = db_path
    else:
        cfg["db_path"] = _resolve_slot_db_path(cfg, project_root=project_root)
    if not novel_title:
        novel_title = cfg.get("default_novel_title", novel_slug)
    return App(
        cfg, novel_slug, novel_title, volume_no, chapters_dir,
        project_root=project_root, config_path=config_path,
    )


def _reports_dir(app) -> Path:
    """与 post.py 保持一致：报告落在 exports/reports。"""
    d = app.exports_root / "reports"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _revised_path(chapter_file: Path, chapter_no: int) -> Path:
    """revised 稿与原稿同目录，固定命名便于 accept 定位。"""
    return chapter_file.parent / f"chapter_{chapter_no:03d}_revised.txt"


def _merged_guidance(tasks) -> tuple:
    """合并所有任务的 must_keep/avoid（各任务现在可能不同类），去重保序。"""
    keep, avoid = [], []
    for t in tasks:
        keep.extend(t.get("must_keep", []))
        avoid.extend(t.get("avoid", []))
    return list(dict.fromkeys(keep)), list(dict.fromkeys(avoid))


def _build_rewrite_card(chapter_no, chapter_text, tasks, chapter_file, revised_path) -> str:
    """把任务拼成 markdown 改写卡，供 Agent 改写。

    这些都是**章节级**风格问题，不再伪造段落定位——卡按类别呈现，正文 Agent 已持有全文。
    """
    lines = [
        f"# 第{chapter_no}章 改写卡",
        "",
        f"- 原稿: `{chapter_file}`",
        f"- 改稿请写到: `{revised_path}`",
        f"- 任务数: {len(tasks)}",
        "",
        "## 总则（每个任务都适用）",
        "",
    ]
    keep, avoid = _merged_guidance(tasks)
    for k in keep:
        lines.append(f"- 必须保留: {k}")
    for a in avoid:
        lines.append(f"- 禁止: {a}")
    lines.append("")
    lines.append("## 改写要求：全文已在你手上，只修下列类别问题，其余原样保留")
    lines.append("")

    for task in tasks:
        lines.extend([
            f"### {task['task_id']}（{task['type']}，置信度 {task['confidence']}）",
            "",
            f"- 问题: {task.get('problem', '')}",
            f"- 指令: {task.get('instruction', '')}",
        ])
        evidence = task.get("evidence") or []
        if evidence:
            lines.append("- 例句（来自门禁证据）:")
            for ev in evidence[:3]:
                lines.append(f"  > {ev}")
        lines.append("")

    lines.extend([
        "---",
        "改写完成后，把全章（已修改 + 未修改段落）完整写入上方 `改稿请写到` 路径，",
        "再运行 `nf_pipeline action=accept` 做 diff 审核与入库。",
        f"*Generated by rewrite {get_version()}*",
        "",
    ])
    return "\n".join(lines)


def run_rewrite(
    chapter_no,
    chapter_type="normal",
    novel_slug="demo_novel",
    novel_title="",
    volume_no=1,
    chapters_dir=None,
    db_path=None,
    project_root=None,
    config_path=None,
    min_confidence=0.70,
    max_tasks=5,
    context=None,
):
    """产改写卡 + revision_tasks.json。不调 LLM。"""
    if context is None:
        context = _build_context(novel_slug, novel_title, volume_no,
                                 chapters_dir, db_path, project_root, config_path)
    app = context

    chapter_file = find_chapter_file_with_fallback(chapter_no, app)
    if not chapter_file:
        return {"status": "error", "message": f"找不到第{chapter_no}章 TXT"}

    chapter_text = _strip_selfcheck(chapter_file.read_text(encoding="utf-8")).strip()

    reports_dir = _reports_dir(app)
    dedup_path = reports_dir / f"chapter_{chapter_no:03d}_deduplicated_report.json"
    if not dedup_path.exists():
        return {
            "status": "error",
            "message": f"缺少去重报告 {dedup_path.name}，请先跑 post。",
        }
    report = json.loads(dedup_path.read_text(encoding="utf-8"))
    report.setdefault("chapter_no", chapter_no)

    bundle = generate_tasks(chapter_text, report,
                            min_confidence=min_confidence, max_tasks=max_tasks)
    tasks = bundle["tasks"]
    bundle["source_file"] = str(chapter_file)

    revised_path = _revised_path(chapter_file, chapter_no)

    # 持久化任务，供 accept 阶段复用（首次真正落盘 revision_tasks.json）
    tasks_path = reports_dir / f"chapter_{chapter_no:03d}_revision_tasks.json"
    write_json_atomic(tasks_path, bundle)

    card_md = _build_rewrite_card(chapter_no, chapter_text, tasks, chapter_file, revised_path)
    card_dir = app.outputs_root / "rewrite_cards"
    card_dir.mkdir(parents=True, exist_ok=True)
    card_path = card_dir / f"chapter_{chapter_no:03d}_rewrite_card.md"
    card_path.write_text(card_md, encoding="utf-8")

    # 语义保全：产契约 + host 请求卡（让 host 改写时就知道"什么必须留住"），fail-open。
    req_json, req_md, verdict_path = _semantic_paths(app, chapter_file, chapter_no)
    semantic_request_path = ""
    try:
        contract = build_preservation_contract(app, chapter_no, chapter_text)
        write_review_request(contract, None, req_json, req_md, verdict_path)
        semantic_request_path = str(req_json)
    except Exception as _e:
        from src.utils.error_handling import log_optional_failure
        log_optional_failure("rewrite: 语义保全请求卡", _e)

    return {
        "status": "ok",
        "chapter_no": chapter_no,
        "task_count": len(tasks),
        "card_path": str(card_path),
        "tasks_path": str(tasks_path),
        "revised_expected_path": str(revised_path),
        "semantic_request_path": semantic_request_path,
        "semantic_card_path": str(req_md),
        "message": bundle["message"],
    }


def _compute_changed_ranges(source_text, revised_text) -> list:
    """全文段落对齐：difflib 扫出**所有**变动段落块（含任务区间外），不再漏记。

    任务已不带段落范围（章节尺度），故这里产出的是文档级改动图，供人审与验证参考，
    不再按 task_id 归属。"""
    src = split_paragraphs(source_text)
    rev = split_paragraphs(revised_text)
    sm = difflib.SequenceMatcher(None, src, rev)
    changed = []
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            continue
        changed.append({
            "change_type": tag,                        # replace / insert / delete
            "source_paragraphs": [i1 + 1, i2] if i2 > i1 else [],
            "revised_paragraphs": [j1 + 1, j2] if j2 > j1 else [],
        })
    return changed


def _verify_with_guard_rerun(app, revised_text, chapter_no, tasks, reports_dir) -> dict:
    """在 revised 上重跑 guard，按类别比对『是否真修了原问题』。整段 fail-open。

    - resolved: 任务类别在 revised 已不再被检出（问题消失）。
    - persisted: 任务类别在 revised 仍在。
    - regressed: revised 冒出的、既不在原始去重报告也不在任务集中的新类别（改写引入了新问题）。
    真正的语义保全（伏笔/情节）需 LLM，不在此列——这里只做确定性的类别级回归比对。
    """
    try:
        from src.pipeline.guard_orchestrator import run_orchestrated
        from src.pipeline.report_deduplicator import deduplicate_warnings
        from src.pipeline.revision_task_generator import _LABEL_TO_CAT

        verify_dir = reports_dir / "_verify"
        verify_dir.mkdir(parents=True, exist_ok=True)
        cfg = getattr(app, "cfg", None) or {}
        orch = run_orchestrated(
            revised_text, chapter_no, mode="standard", config=cfg,
            reports_dir=str(verify_dir), prev_tail="", prev_brief=None,
            extra_context=None)
        merged = deduplicate_warnings(orch.get("warnings", []), 0.55)
        revised_cats = {c for c in
                        (_LABEL_TO_CAT.get(m.get("merged_issue", "")) for m in merged) if c}

        # 原始去重报告类别作为回归基线（best-effort）
        baseline_cats = set()
        dedup_path = reports_dir / f"chapter_{chapter_no:03d}_deduplicated_report.json"
        if dedup_path.exists():
            try:
                orig = json.loads(dedup_path.read_text(encoding="utf-8"))
                baseline_cats = {c for c in
                                 (_LABEL_TO_CAT.get(mi.get("merged_issue", ""))
                                  for mi in orig.get("merged_issues", [])) if c}
            except (OSError, json.JSONDecodeError):
                pass

        task_cats = {t.get("category") for t in tasks
                     if t.get("category") and t.get("category") != "UNCATEGORIZED"}
        return {
            "available": True,
            "mode": "standard",
            "revised_issue_count": len(merged),
            "revised_categories": sorted(revised_cats),
            "resolved": sorted(task_cats - revised_cats),
            "persisted": sorted(task_cats & revised_cats),
            "regressed": sorted(revised_cats - (baseline_cats | task_cats)),
        }
    except Exception as e:
        return {"available": False, "reason": str(e)}


def run_accept(
    chapter_no,
    chapter_type="normal",
    novel_slug="demo_novel",
    novel_title="",
    volume_no=1,
    chapters_dir=None,
    db_path=None,
    project_root=None,
    config_path=None,
    ingest=False,
    enforce_preservation=None,
    context=None,
):
    """原文 vs revised 做 diff；ingest=True 且未被拒绝时入库。不调 LLM。

    enforce_preservation: 语义保全 broken 时是否硬阻入库（None → 读 cfg
    `semantic_preservation.enforce`，默认 False = 仅勝告）。"""
    if context is None:
        context = _build_context(novel_slug, novel_title, volume_no,
                                 chapters_dir, db_path, project_root, config_path)
    app = context

    chapter_file = find_chapter_file_with_fallback(chapter_no, app)
    if not chapter_file:
        return {"status": "error", "message": f"找不到第{chapter_no}章 TXT"}

    revised_path = _revised_path(chapter_file, chapter_no)
    if not revised_path.exists():
        return {
            "status": "error",
            "message": f"缺少改稿 {revised_path.name}，请先按改写卡写 revised.txt。",
        }

    source_text = _strip_selfcheck(chapter_file.read_text(encoding="utf-8")).strip()
    revised_text = _strip_selfcheck(revised_path.read_text(encoding="utf-8")).strip()

    reports_dir = _reports_dir(app)
    tasks_path = reports_dir / f"chapter_{chapter_no:03d}_revision_tasks.json"
    tasks = []
    if tasks_path.exists():
        try:
            tasks = json.loads(tasks_path.read_text(encoding="utf-8")).get("tasks", [])
        except (OSError, json.JSONDecodeError):
            tasks = []

    changed_ranges = _compute_changed_ranges(source_text, revised_text)

    # guard 复跑验证：仅当确有改动时跑一次（空改无意义且省去重活），fail-open。
    verification = None
    if revised_text != source_text:
        verification = _verify_with_guard_rerun(
            app, revised_text, chapter_no, tasks, reports_dir)

    # 语义保全：重建契约 → 词级预检 + 读 host 回执 → 评估（fail-open）。
    if enforce_preservation is None:
        enforce_preservation = bool(
            (getattr(app, "cfg", None) or {}).get("semantic_preservation", {}).get("enforce", False))
    preservation = None
    if revised_text != source_text:
        try:
            _, _, verdict_path = _semantic_paths(app, chapter_file, chapter_no)
            contract = build_preservation_contract(app, chapter_no, source_text)
            precheck = lexical_precheck(contract, revised_text)
            verdict = read_verdict(verdict_path)
            preservation = evaluate_preservation(
                contract, precheck, verdict, enforce=enforce_preservation)
        except Exception as _e:
            from src.utils.error_handling import log_optional_failure
            log_optional_failure("accept: 语义保全评估", _e)
            preservation = {"available": False}

    rewrite_log = {
        "version": get_version(),
        "chapter_no": chapter_no,
        "source": str(chapter_file),
        "output": str(revised_path),
        "changed_ranges": changed_ranges,
        "verification": verification or {"available": False},
        "preservation": preservation or {"available": False},
    }

    diff = generate_diff_report(source_text, revised_text, rewrite_log, tasks,
                                verification=verification, preservation=preservation)

    log_path = reports_dir / f"chapter_{chapter_no:03d}_rewrite_log.json"
    diff_path = reports_dir / f"chapter_{chapter_no:03d}_revision_diff_report.json"
    write_json_atomic(log_path, rewrite_log)
    write_json_atomic(diff_path, diff)

    result = {
        "status": "ok",
        "chapter_no": chapter_no,
        "recommendation": diff["recommendation"],
        "risk_flags": diff["risk_flags"],
        "summary": diff["summary"],
        "verification": diff["verification"],
        "preservation": diff["preservation"],
        "diff_report_path": str(diff_path),
        "rewrite_log_path": str(log_path),
        "ingested": False,
    }

    if ingest:
        # 空改拦截 + 拒绝拦截：revised≈原文（NO_CHANGE_DETECTED）或被拒，一律不入库。
        if diff["recommendation"] in ("REVISION_REJECTED", "NO_CHANGE_DETECTED"):
            result["ingest_skipped_reason"] = f"recommendation={diff['recommendation']}，未入库。"
            return result
        # 提升 revised 为 canonical；旧稿已在 post 阶段进 chapter_versions 快照。
        ingest_result = ingest_chapter(
            chapter_no,
            chapter_type,
            app_inst=app,
            content_override=revised_text,
        )
        if ingest_result is None:
            result["status"] = "error"
            result["message"] = "ingest 失败"
            return result
        result["ingested"] = True

    return result
