#!/usr/bin/env python3
"""rewrite.py — 改写闭环（产改写卡 + diff/入库），内核不调 LLM。

时序: pre → 写 → post → [rewrite] → Agent 改写 → [accept]

- run_rewrite: 读原文 + post 产出的去重报告 → generate_tasks → 写「改写卡」md
  + revision_tasks.json。正文改写由 Agent host 执行，本函数不调任何模型。
- run_accept: 原文 vs revised → generate_diff_report → 写 diff/log；当 ingest=True
  且 recommendation 非 REJECTED 时，把 revised 提升为该章 canonical 并入库（追加
  chapter_versions 快照，永不覆盖原稿）。
"""

import json
from pathlib import Path

from version import get_version
from src.pipeline._base import (
    App,
    find_chapter_file_with_fallback,
    _strip_selfcheck,
    _resolve_slot_db_path,
    load_config,
    write_json_atomic,
)
from src.pipeline.revision_task_generator import generate_tasks, split_paragraphs
from src.pipeline.revision_diff_report import generate_diff_report
from src.pipeline.ingest import ingest as ingest_chapter


def _build_context(novel_slug, novel_title, volume_no, chapters_dir,
                   db_path, project_root, config_path):
    """构建 App，沿用 run_post 的 context-or-build 模式。"""
    cfg = load_config(config_path, project_root=project_root)
    if db_path:
        cfg["db_path"] = db_path
    else:
        cfg["db_path"] = _resolve_slot_db_path(cfg, project_root=project_root)
    if not novel_title:
        novel_title = cfg.get("default_novel_title", novel_slug)
    return App(
        cfg, novel_slug, novel_title, volume_no, chapters_dir,
        project_root=project_root, config_path=config_path,
    )


def _reports_dir(app) -> Path:
    """与 post.py 保持一致：报告落在 exports/reports。"""
    d = app.exports_root / "reports"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _revised_path(chapter_file: Path, chapter_no: int) -> Path:
    """revised 稿与原稿同目录，固定命名便于 accept 定位。"""
    return chapter_file.parent / f"chapter_{chapter_no:03d}_revised.txt"


def _merged_guidance(tasks) -> tuple:
    """合并所有任务的 must_keep/avoid（各任务现在可能不同类），去重保序。"""
    keep, avoid = [], []
    for t in tasks:
        keep.extend(t.get("must_keep", []))
        avoid.extend(t.get("avoid", []))
    return list(dict.fromkeys(keep)), list(dict.fromkeys(avoid))


def _build_rewrite_card(chapter_no, chapter_text, tasks, chapter_file, revised_path) -> str:
    """把任务拼成 markdown 改写卡，供 Agent 改写。

    这些都是**章节级**风格问题，不再伪造段落定位——卡按类别呈现，正文 Agent 已持有全文。
    """
    lines = [
        f"# 第{chapter_no}章 改写卡",
        "",
        f"- 原稿: `{chapter_file}`",
        f"- 改稿请写到: `{revised_path}`",
        f"- 任务数: {len(tasks)}",
        "",
        "## 总则（每个任务都适用）",
        "",
    ]
    keep, avoid = _merged_guidance(tasks)
    for k in keep:
        lines.append(f"- 必须保留: {k}")
    for a in avoid:
        lines.append(f"- 禁止: {a}")
    lines.append("")
    lines.append("## 改写要求：全文已在你手上，只修下列类别问题，其余原样保留")
    lines.append("")

    for task in tasks:
        lines.extend([
            f"### {task['task_id']}（{task['type']}，置信度 {task['confidence']}）",
            "",
            f"- 问题: {task.get('problem', '')}",
            f"- 指令: {task.get('instruction', '')}",
        ])
        evidence = task.get("evidence") or []
        if evidence:
            lines.append("- 例句（来自门禁证据）:")
            for ev in evidence[:3]:
                lines.append(f"  > {ev}")
        lines.append("")

    lines.extend([
        "---",
        "改写完成后，把全章（已修改 + 未修改段落）完整写入上方 `改稿请写到` 路径，",
        "再运行 `nf_pipeline action=accept` 做 diff 审核与入库。",
        f"*Generated by rewrite {get_version()}*",
        "",
    ])
    return "\n".join(lines)


def run_rewrite(
    chapter_no,
    chapter_type="normal",
    novel_slug="demo_novel",
    novel_title="",
    volume_no=1,
    chapters_dir=None,
    db_path=None,
    project_root=None,
    config_path=None,
    min_confidence=0.70,
    max_tasks=5,
    context=None,
):
    """产改写卡 + revision_tasks.json。不调 LLM。"""
    if context is None:
        context = _build_context(novel_slug, novel_title, volume_no,
                                 chapters_dir, db_path, project_root, config_path)
    app = context

    chapter_file = find_chapter_file_with_fallback(chapter_no, app)
    if not chapter_file:
        return {"status": "error", "message": f"找不到第{chapter_no}章 TXT"}

    chapter_text = _strip_selfcheck(chapter_file.read_text(encoding="utf-8")).strip()

    reports_dir = _reports_dir(app)
    dedup_path = reports_dir / f"chapter_{chapter_no:03d}_deduplicated_report.json"
    if not dedup_path.exists():
        return {
            "status": "error",
            "message": f"缺少去重报告 {dedup_path.name}，请先跑 post。",
        }
    report = json.loads(dedup_path.read_text(encoding="utf-8"))
    report.setdefault("chapter_no", chapter_no)

    bundle = generate_tasks(chapter_text, report,
                            min_confidence=min_confidence, max_tasks=max_tasks)
    tasks = bundle["tasks"]
    bundle["source_file"] = str(chapter_file)

    revised_path = _revised_path(chapter_file, chapter_no)

    # 持久化任务，供 accept 阶段复用（首次真正落盘 revision_tasks.json）
    tasks_path = reports_dir / f"chapter_{chapter_no:03d}_revision_tasks.json"
    write_json_atomic(tasks_path, bundle)

    card_md = _build_rewrite_card(chapter_no, chapter_text, tasks, chapter_file, revised_path)
    card_dir = app.outputs_root / "rewrite_cards"
    card_dir.mkdir(parents=True, exist_ok=True)
    card_path = card_dir / f"chapter_{chapter_no:03d}_rewrite_card.md"
    card_path.write_text(card_md, encoding="utf-8")

    return {
        "status": "ok",
        "chapter_no": chapter_no,
        "task_count": len(tasks),
        "card_path": str(card_path),
        "tasks_path": str(tasks_path),
        "revised_expected_path": str(revised_path),
        "message": bundle["message"],
    }


def _compute_changed_ranges(source_text, revised_text, tasks) -> list:
    """段落级定位：任务范围内有段落变化即记为 APPLIED。"""
    src = split_paragraphs(source_text)
    rev = split_paragraphs(revised_text)
    changed = []
    for task in tasks:
        rng = task.get("target_range", {})
        start = rng.get("paragraph_start", 1)
        end = rng.get("paragraph_end", start)
        touched = False
        for i in range(start, end + 1):
            s = src[i - 1] if 1 <= i <= len(src) else ""
            r = rev[i - 1] if 1 <= i <= len(rev) else ""
            if s != r:
                touched = True
                break
        if touched:
            changed.append({
                "task_id": task["task_id"],
                "paragraph_start": start,
                "paragraph_end": end,
                "change_type": "rewrite_range",
                "reason": task.get("instruction", "")[:40],
            })
    return changed


def run_accept(
    chapter_no,
    chapter_type="normal",
    novel_slug="demo_novel",
    novel_title="",
    volume_no=1,
    chapters_dir=None,
    db_path=None,
    project_root=None,
    config_path=None,
    ingest=False,
    context=None,
):
    """原文 vs revised 做 diff；ingest=True 且未被拒绝时入库。不调 LLM。"""
    if context is None:
        context = _build_context(novel_slug, novel_title, volume_no,
                                 chapters_dir, db_path, project_root, config_path)
    app = context

    chapter_file = find_chapter_file_with_fallback(chapter_no, app)
    if not chapter_file:
        return {"status": "error", "message": f"找不到第{chapter_no}章 TXT"}

    revised_path = _revised_path(chapter_file, chapter_no)
    if not revised_path.exists():
        return {
            "status": "error",
            "message": f"缺少改稿 {revised_path.name}，请先按改写卡写 revised.txt。",
        }

    source_text = _strip_selfcheck(chapter_file.read_text(encoding="utf-8")).strip()
    revised_text = _strip_selfcheck(revised_path.read_text(encoding="utf-8")).strip()

    reports_dir = _reports_dir(app)
    tasks_path = reports_dir / f"chapter_{chapter_no:03d}_revision_tasks.json"
    tasks = []
    if tasks_path.exists():
        try:
            tasks = json.loads(tasks_path.read_text(encoding="utf-8")).get("tasks", [])
        except (OSError, json.JSONDecodeError):
            tasks = []

    changed_ranges = _compute_changed_ranges(source_text, revised_text, tasks)
    rewrite_log = {
        "version": get_version(),
        "chapter_no": chapter_no,
        "source": str(chapter_file),
        "output": str(revised_path),
        "changed_ranges": changed_ranges,
    }

    diff = generate_diff_report(source_text, revised_text, rewrite_log, tasks)

    log_path = reports_dir / f"chapter_{chapter_no:03d}_rewrite_log.json"
    diff_path = reports_dir / f"chapter_{chapter_no:03d}_revision_diff_report.json"
    write_json_atomic(log_path, rewrite_log)
    write_json_atomic(diff_path, diff)

    result = {
        "status": "ok",
        "chapter_no": chapter_no,
        "recommendation": diff["recommendation"],
        "risk_flags": diff["risk_flags"],
        "summary": diff["summary"],
        "diff_report_path": str(diff_path),
        "rewrite_log_path": str(log_path),
        "ingested": False,
    }

    if ingest:
        if diff["recommendation"] == "REVISION_REJECTED":
            result["ingest_skipped_reason"] = "recommendation=REVISION_REJECTED，未入库。"
            return result
        # 提升 revised 为 canonical；旧稿已在 post 阶段进 chapter_versions 快照。
        chapter_file.write_text(revised_text, encoding="utf-8")
        ingest_result = ingest_chapter(chapter_no, chapter_type, app_inst=app)
        if ingest_result is None:
            result["status"] = "error"
            result["message"] = "ingest 失败"
            return result
        result["ingested"] = True

    return result
