from typing import Protocol


class BlobStore(Protocol):
    async def put(self, *, data: bytes, media_type: str) -> str: ...

    async def get(self, storage_key: str) -> bytes: ...

    async def delete(self, storage_key: str) -> None: ...

    async def exists(self, storage_key: str) -> bool: ...
